### ISSUE TITLE
evaluate_policy.py - evaluation of multiple seed cant find 'stats.csv'

### ISSUE THREAD

**Issue by stefanwanckel** [PierreExeter/rl_reach#4]
evaluate_policy.py works fine for one seed (--log-info 0).
However, evaluating with more than one seed yields the following error for every seed:

> Traceback (most recent call last):
  File "scripts/plot_training_1seed.py", line 35, in <module>
    df = pd.read_csv(log_dir + 'stats.csv')
  File "/home/stefan/anaconda3/envs/rl_reach/lib/python3.7/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/stefan/anaconda3/envs/rl_reach/lib/python3.7/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/stefan/anaconda3/envs/rl_reach/lib/python3.7/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/stefan/anaconda3/envs/rl_reach/lib/python3.7/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/stefan/anaconda3/envs/rl_reach/lib/python3.7/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/home/stefan/anaconda3/envs/rl_reach/lib/python3.7/site-packages/pandas/io/parsers.py", line 1368, in _open_handles
    storage_options=kwds.get("storage_options", None),
  File "/home/stefan/anaconda3/envs/rl_reach/lib/python3.7/site-packages/pandas/io/common.py", line 647, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'logs/exp_999/ppo/widowx_reacher-v1_3/stats.csv'

The file 'stats.csv' does not exist in any of the seed folders. 
I would be happy about some hints on how to solve this.
Thanks in advance for your help.

**Comment by stefanwanckel** [comment]
Addendum:
When evaluating a policy with '--algo her', the 'stats.csv' is also missing. So maybe this issue is unrelated to the number of seeds.

**Comment by PierreExeter** [comment]
stats.csv is created by the enjoy.py script. It should be written for every seed folder, independently on whether you use 1 or more seeds. Can you send the exact command that return this error?

**Comment by stefanwanckel** [comment]
It works now. I had a typo. Thanks for the quick reply
